### ISSUE TITLE
Why is `putIfAbsent` not idempotent

### ISSUE THREAD

**Issue by ddlatham** [ravichaturvedi/retrier#10]
The readme gives examples of operations that are idempotent and others that are not.

Why is map.putIfAbsent(1, 2) not considered idempotent?  Executing it more than once would seem to produce the same resulting map as executing it once.

**Comment by ravichaturvedi** [comment]
That's true from user perspective putIfAbsent will be an idempotent operation if we consider that example in isolation. 

However, I tried to put that as an example of non-idempotent operation so that it should be carefully used during compound operation retry, as in below pseudocode:

```java
Map<String, String> m;
retry(() -> {
  m.putIfAbsent(key, loadFromDatabase());
  if (someCondition) {
     throw new Exception();
  }
  String value = m.get(key);
  return someComputation(value);
})
```

Here if `someCondition` is true then the entire block will be retried (as exception thrown) but since we already updated the map state in the earlier run that will result in the inconsistent result for the returned value from retry block if the database state doesn't match the map state at the time of subsequent retry.

**Comment by ddlatham** [comment]
I think what your example illustrates is that just because individual operations are idempotent, doesn't mean that composing them results in another idempotent operation.
In this case, even though `putIfAbsent` is idempotent, when you create a new operation by composing it with others (such as `loadFromDatabase`) then the result is not idempotent.

One could construct another example with operations listed as examples of idempotency such as `get` and `put`:

    Map<String, String> m1, m2;
    retry(() -> {
        String temp = m2.get("key");
        m2.put("key", m1.get("key"));
        m1.put("key", temp);
    })

Here, if the operation is done once, the values are swapped, but if it is retried and done twice, the values are swapped back.  So, while each get or put individually would be idempotent, the operation as a whole is not.

**Comment by ravichaturvedi** [comment]
I agree. Perhaps we need more clarity in the documentation.
Would be glad to accept your Pull Request!

**Comment by ravichaturvedi** [comment]
@ddlatham Thanks for the PR #11. 
Closing this issue as the PR got merged.
